#!/usr/bin/env python

from apns import APNs, Payload
import random

import optparse

parser = optparse.OptionParser()

parser.add_option("-c", "--certificate-file",
                  dest="certificate_file",
                  help="Path to .pem certificate file")

parser.add_option("-p", "--push-token",
                  dest="push_token",
                  help="Push token")

parser.add_option("-m", "--message",
                  dest="message",
                  help="Message")

options, args = parser.parse_args()

if options.certificate_file is None:
    parser.error('Must provide --certificate-file')

if options.push_token is None:
    parser.error('Must provide --push-token')

if options.message is None:
    parser.error('Must provide --message')

apns = APNs(cert_file=options.certificate_file, use_sandbox=True)

# Send a notification
payload = Payload(alert=options.message, sound="default", badge=1)
identifier = random.getrandbits(32)
apns.gateway_server.send_notification(options.push_token, payload, identifier=identifier)
print("Sent push message to APNS gateway.")


# Get feedback messages.
for (token_hex, fail_time) in apns.feedback_server.items():
    print 'E', token_hex, fail_time
